# Generated by Django 4.2.2 on 2023-06-19 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('client', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_type', models.CharField(choices=[('standard', 'Standard Queue'), ('priority', 'Priority Queue'), ('vip', 'VIP Queue')], default='standard', max_length=20)),
                ('priority', models.BooleanField(default=False)),
                ('queue_length', models.IntegerField(default=0)),
                ('standard_service_time', models.DurationField(blank=True, null=True)),
                ('priority_service_time', models.DurationField(blank=True, null=True)),
                ('vip_service_time', models.DurationField(blank=True, null=True)),
                ('max_limit', models.IntegerField(default=1000)),
                ('is_paused', models.BooleanField(default=False)),
                ('max_waiting_time', models.PositiveIntegerField(default=0)),
                ('queue_group', models.CharField(max_length=100)),
                ('average_service_time', models.IntegerField()),
                ('max_service_time', models.IntegerField()),
                ('start_of_day', models.TimeField()),
                ('end_of_day', models.TimeField()),
                ('description', models.TextField()),
                ('queue_start_time', models.TimeField(blank=True, null=True)),
                ('queue_end_time', models.TimeField(blank=True, null=True)),
                ('general_calendar', models.DateField(blank=True, null=True)),
                ('individual_calendar', models.DateField(blank=True, null=True)),
                ('is_automatic_calling_enabled', models.BooleanField(default=True)),
                ('max_auto_automatic_calling', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_queues', to='operators.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('STANDARD', 'Standard'), ('PRIORITY', 'Priority'), ('VIP', 'Vip')], default='STANDARD', max_length=10)),
                ('service_time', models.DurationField(default=datetime.timedelta(0))),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='operators.operator')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue.queue')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_time', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tickets', to='client.client')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tickets', to='queue.queue')),
            ],
        ),
    ]
