# Generated by Django 4.1.7 on 2023-06-16 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("operators", "0001_initial"),
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Queue"),
                            ("priority", "Priority Queue"),
                            ("vip", "VIP Queue"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("priority", models.BooleanField(default=False)),
                ("queue_length", models.IntegerField(default=0)),
                ("standard_service_time", models.DurationField()),
                ("priority_service_time", models.DurationField()),
                ("vip_service_time", models.DurationField()),
                ("max_limit", models.IntegerField(default=1000)),
                ("is_paused", models.BooleanField(default=False)),
                ("max_waiting_time", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.branch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_time", models.DateTimeField()),
                ("language", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("PRIORITY", "Priority"),
                            ("VIP", "Vip"),
                        ],
                        default="STANDARD",
                        max_length=10,
                    ),
                ),
                ("service_time", models.DurationField(default=datetime.timedelta(0))),
                ("wait_time", models.DurationField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.branch"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                    ),
                ),
                (
                    "operator",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talon_tickets",
                        to="operators.operator",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="queue.queue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="queue.ticket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservedTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("service_time", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_tickets",
                        to="client.client",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_tickets",
                        to="queue.queue",
                    ),
                ),
            ],
        ),
    ]
