# Generated by Django 4.2.2 on 2023-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='general_calendar',
            field=models.CharField(choices=[('normal', 'Normal'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('pandemic', 'Pandemic')], default='normal', max_length=20),
        ),
    ]
