# Generated by Django 4.1.7 on 2023-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRIORITY", "Priority"),
                    ("VIP", "Vip"),
                ],
                default="STANDARD",
                max_length=10,
            ),
        ),
    ]
