# Generated by Django 4.1.7 on 2023-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0002_ticket_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="max_limit",
            field=models.IntegerField(default=1000),
        ),
    ]
