# Generated by Django 4.1.7 on 2023-06-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operators", "0001_initial"),
        ("queue", "0002_alter_reservedticket_service_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="operators.operator",
            ),
        ),
    ]
