# Generated by Django 4.2.2 on 2023-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_alter_queue_general_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='general_calendar',
            field=models.CharField(choices=[('normal', 'Normal'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('half-day', 'Half-day')], default='normal', max_length=20),
        ),
    ]
