# Generated by Django 4.2.2 on 2023-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0003_alter_queue_general_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='queue_group',
        ),
        migrations.AlterField(
            model_name='queue',
            name='average_service_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='end_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='max_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='start_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
