# Generated by Django 4.1.7 on 2023-06-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operators", "0001_initial"),
        ("queue", "0003_queue_max_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="operator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="talon_tickets",
                to="operators.operator",
            ),
        ),
    ]
