# Generated by Django 4.1.7 on 2023-06-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0004_ticket_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="service_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
