# Generated by Django 4.1.7 on 2023-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0005_ticket_service_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="wait_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
