# Generated by Django 4.1.7 on 2023-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queue", "0001_initial"),
        ("client", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedticket",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="queue.queue"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="client_users", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="client_users", to="auth.permission"
            ),
        ),
    ]
