from django.urls import path
from .views import *

urlpatterns = [
    path('queues/', create_queue, name='create_queue'),
    path('queues/<int:queue_id>/', get_queue, name='get_queue'),
    path('queues/<int:queue_id>/update/', update_queue, name='update_queue'),
    path('queues/<int:queue_id>/delete/', delete_queue, name='delete_queue'),
    path('queues/<int:queue_id>/tickets/', get_tickets_in_queue, name='get_tickets_in_queue'),
    path('queues/<int:queue_id>/status/', get_queue_status, name='get_queue_status'),
    path('queues/<int:queue_id>/generate-ticket/', generate_ticket, name='generate_ticket'),
    path('queues/<int:queue_id>/call-next-ticket/', call_next_ticket, name='call_next_ticket'),
    path('tickets/<int:ticket_id>/delete/', delete_ticket, name='delete_ticket'),
    path('tickets/<int:ticket_id>/move-to-queue/<int:new_queue_id>/', move_ticket_to_queue, name='move_ticket_to_queue'),
    path('tickets/<int:ticket_id>/update-status/', update_ticket_status, name='update_ticket_status'),
    path('tickets/waiting/', get_waiting_tickets, name='get_waiting_tickets'),
    path('tickets/served/', get_served_tickets, name='get_served_tickets'),
    path('queues/<int:queue_id>/ticket-count/', get_total_tickets, name='get_total_tickets'),
    path('queues/<int:queue_id>/average-wait-time/', calculate_average_wait_time, name='calculate_average_wait_time'),
    path('queues/<int:queue_id>/branch-info/', get_branch_info, name='get_branch_info'),
    path('tickets/<int:ticket_id>/send-notification/', send_ticket_notification, name='send_ticket_notification'),
    path('tickets/search/<str:ticket_number>/', search_ticket_by_number, name='search_ticket_by_number'),
    path('branches/<int:branch_id>/queues/', search_queues_by_branch, name='search_queues_by_branch'),
    path('queues/search/', search_queues_by_name, name='search_queues_by_name'),
    path('queues/sort/<str:sort_by>/', sort_queues, name='sort_queues'),
    path('tickets/<int:ticket_id>/priority/update/', set_ticket_priority, name='set_ticket_priority'),
    path('queues/<int:queue_id>/max-limit/update/', set_max_ticket_limit, name='set_max_ticket_limit'),
    path('tickets/<int:ticket_id>/remaining-time/', get_ticket_remaining_time, name='get_ticket_remaining_time'),
    path('tickets/<int:ticket_id>/assign/<int:operator_id>/', assign_ticket_to_operator, name='assign_ticket_to_operator'),
    path('tickets/<int:ticket_id>/delay/<int:delay_minutes>/', delay_ticket_service, name='delay_ticket_service'),
    path('queues/<int:queue_id>/service-time/predicted/', calculate_predicted_waiting_time, name='calculate_predicted_waiting_time'),
    path('tickets/<int:ticket_id>/update-customer-info/', update_customer_info, name='update_customer_info'),
    path('queues/<int:queue_id>/pause/', pause_queue, name='pause_queue'),
    path('queues/<int:queue_id>/resume/', resume_queue, name='resume_queue'),
    path('queues/most-loaded/', get_most_loaded_queues, name='get_most_loaded_queues'),
    path('queues/least-loaded/', get_least_loaded_queues, name='get_least_loaded_queues'),
    path('queues/<int:queue_id>/max-waiting-time/update/', set_max_waiting_time, name='set_max_waiting_time'),
    path('tickets/<int:ticket_id>/priority/<str:new_priority>/update/', change_ticket_priority, name='change_ticket_priority'),
    path('queues/<int:queue_id>/current-waiting-time/', get_current_waiting_time, name='get_current_waiting_time'),
    path('tickets/<int:ticket_id>/history/', get_ticket_history, name='get_ticket_history'),
    path('tickets/<int:ticket_id>/review/', submit_review, name='submit_review'),
    path('queues/<int:queue_id>/service-time/statistics/', view_waiting_time_statistics, name='view_waiting_time_statistics'),
    path('queues/<int:queue_id>/reserve-ticket/<int:client_id>/', reserve_ticket, name='reserve-ticket'),
    path('generate_ticket_send_mail/<int:queue_id>/', generate_ticket_send_mail, name='generate_ticket'),
    path('tickets/<int:ticket_id>/call-to-operator/<int:operator_id>/', call_ticket_to_operator, name='call_ticket_to_operator'),
    path('tickets/<int:queue_id>/call-next-available-operator/', call_next_available_operator, name='call_next_available_operator'),
    path('operators/status/', get_operators_status, name='operators_status'),
]