<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-16 12:06
=======
# Generated by Django 4.1.7 on 2023-06-16 20:25
>>>>>>> ab43b1fe5b8efee48a8f6060d4dfd240102951df

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
