# Generated by Django 4.1.7 on 2023-06-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
        ("operators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="branch",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="bank.branch"
            ),
            preserve_default=False,
        ),
    ]
