# Generated by Django 4.1.7 on 2023-06-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0003_alter_ticket_operator"),
        ("operators", "0002_operator_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="current_ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_operator",
                to="queue.ticket",
            ),
        ),
        migrations.AddField(
            model_name="operator",
            name="ticket_in_service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_in_service",
                to="queue.ticket",
            ),
        ),
    ]
