# Generated by Django 4.1.7 on 2023-06-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("queue", "0003_alter_ticket_operator"),
        ("operators", "0004_remove_operator_ticket_in_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="current_ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_in_service",
                to="queue.ticket",
            ),
        ),
    ]
