

# Generated by Django 4.2.2 on 2023-06-11 18:10

# Generated by Django 4.2.2 on 2023-06-09 07:28


# Generated by Django 4.2.2 on 2023-06-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_queueuser_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueuser',
            name='auth_mode',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='call_outside_queue',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='create_and_close_tickets',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='domain_auth',
        ),
        migrations.RemoveField(
            model_name='queueuser',
            name='modify_queue_list',
        ),
        migrations.AlterField(
            model_name='queueuser',
            name='access_level',
            field=models.CharField(max_length=100, verbose_name='ACCESS_LEVELS'),
        ),
        migrations.AlterField(
            model_name='queueuser',
            name='position',
            field=models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('consultant', 'Consultant'), ('manager', 'Manager')], max_length=100, verbose_name='position'),
        ),


        migrations.AlterField(
            model_name='queueuser',
            name='window_number',
            field=models.CharField(max_length=10000, verbose_name='window number'),
        ),


    ]
