# Generated by Django 4.1.7 on 2023-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_queueuser_window_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
