# Generated by Django 4.2.2 on 2023-06-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_queueuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueuser',
            name='position',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('operator', 'Operator'), ('consultant', 'Consultant'), ('manager', 'Manager')], max_length=100, verbose_name='position'),
        ),
    ]
