# Generated by Django 4.1.7 on 2023-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_queueuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
