# Generated by Django 4.1.7 on 2023-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0002_alter_tickethistory_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickethistory",
            name="status",
            field=models.CharField(
                choices=[("completed", "Обслужен"), ("cancelled", "Не обслужен")],
                max_length=255,
            ),
        ),
    ]
