# Generated by Django 4.2.2 on 2023-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0002_ticketarchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
