# Generated by Django 4.1.7 on 2023-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0003_alter_tickethistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
