# Generated by Django 4.2.2 on 2023-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0003_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketarchive",
            name="status",
            field=models.CharField(default="Не подошел", max_length=255),
        ),
    ]
