# Generated by Django 4.2.2 on 2023-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0004_ticketarchive_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status_signal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketarchive",
            name="status_signal",
            field=models.BooleanField(default=True),
        ),
    ]
