# Generated by Django 4.1.7 on 2023-06-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0004_ticket_queued_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="queued_at",
        ),
    ]
