# Generated by Django 4.2.2 on 2023-06-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0005_ticket_status_signal_ticketarchive_status_signal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="ticketarchive",
            name="is_completed",
        ),
    ]
