# Generated by Django 4.2.2 on 2023-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0006_remove_ticket_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outhertalon",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
