# Generated by Django 4.2.2 on 2023-06-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talon", "0007_outhertalon_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketarchive",
            name="number",
            field=models.CharField(max_length=1000),
        ),
    ]
